compiler:
    - gcc

os:
    - linux

before_script:
    ./autogen.sh

language: c

addons:
    apt:
        sources:
            - llvm-toolchain-precise-3.8
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - check
            - valgrind
            - lcov
            - clang-3.8
            - clang-format-3.8
            - llvm-3.8

before_install:
  - gem install coveralls-lcov

script:
    - ./configure --enable-coverage && make && make check && make distcheck
    - clang-format-3.8 -i $(find . -name '*.[ch]') && git diff --exit-code


after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --compat-libtool --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info
  - coveralls-lcov coverage.info
