sudo: required
dist: trusty

compiler:
    - gcc

os:
    - linux

before_script:
    ./autogen.sh

language: c

addons:
    apt:
        packages:
            - check
            - valgrind
            - lcov

before_install:
  - gem install coveralls-lcov

script:
    - lcov --version | grep "1.10"
    - export CC="gcc"
    - ./configure --enable-coverage && make && make check && make distcheck && make check-valgrind

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --compat-libtool --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info
  - coveralls-lcov coverage.info
