sudo: required
dist: trusty

compiler:
    - gcc

os:
    - linux

before_script:
    ./autogen.sh

language: c

addons:
    apt:
        packages:
            - check
            - valgrind
            - lcov

before_install:
  - pip install --user cpp-coveralls

script: ./configure --enable-coverage && make && make check

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
